[theme]
base = "light"
primaryColor = "#4682b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"
showSidebarNavigation = true

[server]
headless = true
runOnSave = true
enableXsrfProtection = true

[logger]
level = "info"

[browser]
serverAddress = "localhost"
gatherUsageStats = false
